CREATE TABLE CITIES(
	CITY_ID NUMBER (3),
	CITY_NAME VARCHAR2(20) NOT NULL,
	
	CONSTRAINT "CITY_ID_PK" PRIMARY KEY ("CITY_ID")
)

SELECT * FROM CITIES

DROP TABLE CITIES;

INSERT INTO CITIES VALUES (1, 'Milano');

CREATE TABLE STATIONS(
	STATION_ID NUMBER (3)
	CONSTRAINT STATION_ID_PK PRIMARY KEY,
	STATION_NAME VARCHAR2(20) NOT NULL,
	CITY_ID NUMBER (3),
	CONSTRAINT CITY_ID_fk FOREIGN KEY (city_id)
 		REFERENCES cities (city_id)
);

SELECT * FROM STATIONS;

CREATE TABLE preferences (
	NAME VARCHAR2(25),
	SQL NUMBER(1),
	Java NUMBER(1),
	HTML NUMBER(1),

	CONSTRAINT NAME_PK PRIMARY KEY (NAME)
)

DROP TABLE preferences;

SELECT * FROM preferences

INSERT INTO preferences (NAME, SQL, Java, HTML) VALUES ('Giovanna', 1, 3, 2);
INSERT INTO preferences (NAME, SQL, Java, HTML) VALUES ('Alessio', 1, 2, 3);
INSERT INTO preferences (NAME, SQL, Java, HTML) VALUES ('Karolina', 1, 3, 2);
INSERT INTO preferences (NAME, SQL, Java, HTML) VALUES ('Ariam',  3, 1, 2);
INSERT INTO preferences (NAME, SQL, Java, HTML) VALUES ('Federico', 2, 3, 1);
INSERT INTO preferences (NAME, SQL, Java, HTML) VALUES ('Arturo', 3, 2, 1);
INSERT INTO preferences (NAME, SQL, Java, HTML) VALUES ('Virginia', 2, 1, 3);
INSERT INTO preferences (NAME, SQL, Java, HTML) VALUES ('Selena', 2, 3, 1);
INSERT INTO preferences (NAME, SQL, Java, HTML) VALUES ('Giuseppe', 3, 1, 2);
INSERT INTO preferences (NAME, SQL, Java, HTML) VALUES ('Susanna', 2, 1, 3);

delete from preferences
where name = '';


CREATE TABLE BIKE_USERS(
	BU_ID NUMBER(5),
	FIRSTNAME VARCHAR2(25),
	LASTNAME VARCHAR2(25),
	
	CONSTRAINT BU_ID_PK PRIMARY KEY (BU_ID));

SELECT * FROM BIKE_USERS;

DROP TABLE BIKE_USERS;

INSERT INTO BIKE_USERS	(BU_ID, FIRSTNAME, LASTNAME) VALUES (1, 'Giovanna', 'Di Sevo');

DELETE FROM BIKE_USERS
WHERE BU_ID = 1;




CREATE TABLE BIKES (
	BIKE_ID NUMBER(5),
	CITY_ID NUMBER(3),
	STATION_ID NUMBER(3),
	BU_ID NUMBER(5),
	
	CONSTRAINT BIKE_ID_PK PRIMARY KEY (BIKE_ID),
	CONSTRAINT BU_ID_FK FOREIGN KEY (BU_ID)
		REFERENCES BIKE_USERS (BU_ID)
);

DROP TABLE bikes;

SELECT * FROM bikes;


ALTER TABLE preferences
  ADD JAVAScript NUMBER(1);

