CREATE TABLE TYPES (
TYPE_ID NUMBER(5),
TYPE_NAME VARCHAR2(25),
TYPE_IMAGINE VARCHAR2(80),

CONSTRAINT TYPE_ID_PK PRIMARY KEY (TYPE_ID)
);

INSERT INTO TYPES VALUES(1, 'city bike','null');
INSERT INTO TYPES VALUES(2, 'mountain bike','null');
INSERT INTO TYPES VALUES(3, 'BMX bike','null');
INSERT INTO TYPES VALUES(4, 'tandem bike','null');
INSERT INTO TYPES VALUES(5, 'electric bike','null');

SELECT * FROM TYPES;

DROP TABLE TYPES;

DROP TABLE USERS;

CREATE TABLE USERS (
USER_ID NUMBER(5),
USER_NAME VARCHAR2(20) UNIQUE,
USER_PASSWORD VARCHAR2(10),
USER_ROLE VARCHAR2(10),

CONSTRAINT USER_ID_PK PRIMARY KEY (USER_ID)
);

INSERT INTO USERS VALUES(1,'King', 'myshop', 'manager');
INSERT INTO USERS VALUES(2,'Paperino', 'paperina', 'client');

SELECT * FROM USERS;