CREATE TABLE TYPES (
ID NUMBER(5),
TYPE VARCHAR2(25),

CONSTRAINT ID_PK PRIMARY KEY (ID)
);

INSERT INTO TYPES VALUES(1, 'city bike');
INSERT INTO TYPES VALUES(2, 'mountain bike');
INSERT INTO TYPES VALUES(3, 'BMX bike');
INSERT INTO TYPES VALUES(4, 'tandem bike');
INSERT INTO TYPES VALUES(5, 'electric bike');

SELECT * FROM TYPES;

CREATE TABLE USERS (
USER_NAME VARCHAR2(20),
PASSWORD VARCHAR2(10),
ROLE VARCHAR2(10),

CONSTRAINT USER_NAME_PK PRIMARY KEY (USER_NAME)
);

SELECT * FROM USERS;