CREATE TABLE CITIES(
	CITY_ID NUMBER (3),
	CITY_NAME VARCHAR2(20) NOT NULL,
	
	CONSTRAINT "CITY_ID_PK" PRIMARY KEY ("CITY_ID")
)

SELECT * FROM CITIES

DROP TABLE CITIES;

INSERT INTO CITIES VALUES (1, 'Milano');

CREATE TABLE STATIONS(
	STATION_ID NUMBER (3)
	CONSTRAINT STATION_ID_PK PRIMARY KEY,
	STATION_NAME VARCHAR2(20) NOT NULL,
	CITY_ID NUMBER (3),
	CONSTRAINT CITY_ID_fk FOREIGN KEY (city_id)
 		REFERENCES cities (city_id)
);

SELECT * FROM STATIONS;