-- my tables
SELECT DISTINCT OBJECT_NAME
FROM USER_OBJECTS
WHERE OBJECT_TYPE = 'TABLE';

SELECT COUNTRY_ID, COUNTRY_NAME, REGION_ID, REGION_NAME
FROM COUNTRIES NATURAL JOIN REGIONS;

SELECT *
FROM REGIONS;

INSERT INTO REGIONS VALUES(5, 'Oceania');

DELETE FROM REGIONS
WHERE REGION_ID = 5;

SELECT *
FROM COUNTRIES
WHERE REGION_ID = 5;

DELETE FROM COUNTRIES
WHERE COUNTRY_ID = 'TZ';

DELETE FROM COUNTRIES
WHERE REGION_ID = 5;

INSERT INTO COUNTRIES VALUES('CV', 'Vatican City', 1);

SELECT * FROM EMPLOYEES
WHERE JOB_ID = 'IT_PROG';

DELETE FROM EMPLOYEES
WHERE EMAIL = 'JBAUER';

DELETE FROM JOB_HISTORY
WHERE EMPLOYEE_ID = 226;

SELECT * FROM JOB_HISTORY;

INSERT INTO CITIES
VALUES(1, 'Milano');

SELECT * FROM CITIES;

DROP TABLE CITIES;

CREATE TABLE CITIES(
    CITY_ID     NUMBER, 
    CITY_NAME   VARCHAR2(25) NOT NULL,

    CONSTRAINT "CITY_ID_PK" PRIMARY KEY ("CITY_ID")
)

SELECT * FROM EMPLOYEES
WHERE JOB_ID = 'IT_PROG'
ORDER BY EMPLOYEE_ID

-- ManyToMany
CREATE TABLE ORGS(
	ORG_ID NUMBER,
	ORG_NAME VARCHAR2(20) NOT NULL,

	PRIMARY KEY(ORG_ID)
);

DROP TABLE ORGS;

CREATE TABLE ORG_COUNTRY(
	ORG_ID NUMBER,
	COUNTRY_ID CHAR(2),
	
	PRIMARY KEY(ORG_ID, COUNTRY_ID),
	FOREIGN KEY(COUNTRY_ID) REFERENCES COUNTRIES(COUNTRY_ID) ON DELETE CASCADE,
	FOREIGN KEY(ORG_ID) REFERENCES ORGS(ORG_ID) ON DELETE CASCADE
);

DROP TABLE ORG_COUNTRY;

INSERT INTO ORGS VALUES(1, 'EU');
INSERT INTO ORGS VALUES(2, 'NATO');
INSERT INTO ORG_COUNTRY VALUES(1, 'IT');
INSERT INTO ORG_COUNTRY VALUES(1, 'FR');
INSERT INTO ORG_COUNTRY VALUES(2, 'IT');
INSERT INTO ORG_COUNTRY VALUES(2, 'FR');

SELECT C.COUNTRY_NAME, O.ORG_NAME
FROM ORG_COUNTRY NATURAL JOIN ORGS O NATURAL JOIN COUNTRIES C
ORDER BY 1, 2;