-- my tables
SELECT DISTINCT OBJECT_NAME
FROM USER_OBJECTS
WHERE OBJECT_TYPE = 'TABLE';

SELECT COUNTRY_ID, COUNTRY_NAME, REGION_ID, REGION_NAME
FROM COUNTRIES NATURAL JOIN REGIONS;

SELECT *
FROM REGIONS;

INSERT INTO REGIONS VALUES(5, 'Oceania');

DELETE FROM REGIONS
WHERE REGION_ID = 5;

SELECT *
FROM COUNTRIES
WHERE REGION_ID = 1;

DELETE FROM COUNTRIES
WHERE COUNTRY_ID = 'CV';

INSERT INTO COUNTRIES VALUES('CV', 'Vatican City', 1);

SELECT * FROM EMPLOYEES
WHERE JOB_ID = 'IT_PROG';

DELETE FROM EMPLOYEES
WHERE EMAIL = 'JBAUER';

DELETE FROM JOB_HISTORY
WHERE EMPLOYEE_ID = 226;

SELECT * FROM JOB_HISTORY;

INSERT INTO CITIES
VALUES(1, 'Milano');

SELECT * FROM CITIES;

DROP TABLE CITIES;

CREATE TABLE CITIES(
    CITY_ID     NUMBER, 
    CITY_NAME   VARCHAR2(25) NOT NULL,

    CONSTRAINT "CITY_ID_PK" PRIMARY KEY ("CITY_ID")
)

SELECT * FROM EMPLOYEES
WHERE JOB_ID = 'IT_PROG'
ORDER BY EMPLOYEE_ID